import './globals.css'
import { Poppins } from 'next/font/google'

// const poppins = Poppins({subsets:['latin'],weight:['400'],variable:'--font-poppins'})

export const metadata = {
  title: 'Code Mate',
  description: 'Generated by create next app',
  favicon : ''
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
